apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-api
  namespace: study-aws-4-3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-api
  template:
    metadata:
      labels:
        app: task-api
    spec:
      containers:
        - name: api
          image: study-aws-4-3-api:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql+psycopg://app_user:app_password@postgres:5432/tasks
            - name: LOG_LEVEL
              value: INFO
            - name: ENABLE_DEBUG_ERROR_ENDPOINT
              value: "true"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: task-api
  namespace: study-aws-4-3
spec:
  selector:
    app: task-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
